### PR TITLE
Extract embedded objects

### PR DESCRIPTION
**Pull request by FernandoDoming**

### CODE REVIEW

**Comment by jbremer** [comment]
@FernandoDoming which samples belong to this PR again?

**Comment by FernandoDoming** [comment]
This one has an embedded object: c26a351c36ac03aa09f5d98531a103f971b84e22b6a1312bf1dc501421434290

**Comment by jbremer** [comment]
Let's await this thing for now https://github.com/decalage2/oletools/issues/179.

**Comment by jbremer** [comment]
Something very similar to this has been introduced for the upcoming `2.0.5` release. Closing as resolved, thanks though :-)

**Pull request closed without merging**
